# Generated by Django 6.0.3 on 2026-03-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_fix_department_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionstatus',
            name='report_excel',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='submissionstatus',
            name='report_pdf',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
