# Generated by Django 6.0.3 on 2026-03-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_metric_1_1_aqar_year_metric_1_1_3_aqar_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsettings',
            name='aqar_year',
            field=models.CharField(default='2025-26', max_length=10),
        ),
        migrations.AlterField(
            model_name='institutionsettings',
            name='college_name',
            field=models.CharField(default='SIVET College', max_length=255),
        ),
    ]
