# Generated by Django 6.0.3 on 2026-03-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_institutionsettings_aqar_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionstatus',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='submissionstatus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form.department'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionstatus',
            unique_together={('department', 'aqar_year')},
        ),
    ]
