# Generated by Django 6.0.3 on 2026-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_submissionstatus_aqar_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric_1_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_1_1_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_1_2_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_1_2_2_1_2_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_1_3_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_1_3_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_1_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_1_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_4_1_2_4_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_4_2_3_1_2_3_3_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_2_6_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_1_1_3_1_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_2_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_3_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_3_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_4_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_4_3_3_4_4',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_5_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_3_5_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_4_1_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_4_1_4_4_4_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_4_2_2_4_2_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_1_1_5_1_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_1_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_1_4',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_2_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_2_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_2_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_3_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_5_3_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_2_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_3_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_3_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_3_4',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_4_2',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_6_5_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_7_1_1',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_7_1_11',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_7_1_3',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_7_1_4',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
        migrations.AlterField(
            model_name='metric_7_1_5',
            name='aqar_year',
            field=models.CharField(db_index=True, default='2023-24', max_length=10),
        ),
    ]
